### ISSUE TITLE
ئۇيغۇرچىنى تولۇق قوللامدۇ؟

### ISSUE THREAD

**Issue by Sabirjan** [neouyghur/Multiple-Uyghur-Script-Converter#3]
ئەسسالاممۇ ئەلەيكۈم ، بۇ كود ئۇيغۇرچە ھەممە سۆزنى تولۇق قوللامدۇ ياكى ساندانغا ئاساسەن ئالماشتۇرامدۇ؟

**Comment by neouyghur** [comment]
ئەلەيكۇم ئەسسالام، بۇ  پروگرامما ئۇيغۇرچە ھەممە سۆزنى قوللايدۇ. چۈنكى بۇ بىر ھەرپ ئالماشتۇرۇش پروگرامىسى.
